//! Checks this crate against the published vectors in `test-vectors/`, which
//! were generated by an independent implementation. Any client (the SDK, a
//! wallet, a CLI) should pass the same vectors.

use serde_json::Value;
use trustescrow_code::{display, encode, normalise, release_code_hash, CodeError, ALPHABET};

fn vectors() -> Value {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test-vectors/delivery-codes.json"
    )))
    .expect("vectors file is valid JSON")
}

fn cases<'a>(doc: &'a Value, section: &str) -> &'a [Value] {
    doc[section].as_array().expect("section is an array")
}

fn text<'a>(case: &'a Value, field: &str) -> &'a str {
    case[field]
        .as_str()
        .unwrap_or_else(|| panic!("{field} missing in {case}"))
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn alphabet_matches() {
    let doc = vectors();
    assert_eq!(text(&doc, "alphabet").as_bytes(), ALPHABET);
}

#[test]
fn encoding_vectors_match() {
    let doc = vectors();
    let encoding = cases(&doc, "encoding");
    assert!(!encoding.is_empty());
    for case in encoding {
        let entropy: [u8; 10] = unhex(text(case, "entropy_hex")).try_into().unwrap();
        let code = encode(&entropy);
        assert_eq!(
            std::str::from_utf8(&code).unwrap(),
            text(case, "code"),
            "{case}"
        );
        assert_eq!(display(&code), text(case, "display"), "{case}");
        assert_eq!(
            hex(&release_code_hash(&code)),
            text(case, "sha256_hex"),
            "{case}"
        );
    }
}

#[test]
fn normalisation_vectors_match() {
    let doc = vectors();
    let normalisation = cases(&doc, "normalisation");
    assert!(!normalisation.is_empty());
    for case in normalisation {
        let result = normalise(text(case, "input"));
        match (
            case.get("canonical"),
            case.get("error").and_then(Value::as_str),
        ) {
            (Some(canonical), None) => {
                let code = result.unwrap_or_else(|e| panic!("{case}: {e}"));
                assert_eq!(std::str::from_utf8(&code).unwrap(), canonical, "{case}");
                assert_eq!(
                    hex(&release_code_hash(&code)),
                    text(case, "sha256_hex"),
                    "{case}"
                );
            }
            (None, Some("length")) => {
                assert!(
                    matches!(result, Err(CodeError::Length(_))),
                    "{case}: {result:?}"
                )
            }
            (None, Some("character")) => {
                assert!(
                    matches!(result, Err(CodeError::Character(_))),
                    "{case}: {result:?}"
                )
            }
            _ => panic!("malformed vector {case}"),
        }
    }
}
